# application.properties
# 数据库配置信息
server:
  port: 8080
  tomcat:
    max-http-header-size: 8192

spring:
  datasource:
    url: jdbc:mysql://8.138.25.107:3306/note?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=Asia/Shanghai
    username: huanhuan
    password: 991121520L
    driver-class-name: com.mysql.cj.jdbc.Driver
    #MQTT配置
  mqtt:
    #MQTT服务端地址，端口默认为11883，如果有多个，用逗号隔开tcp://aws2.zetakey.com:1883
    url: tcp://aws2.zetakey.com:1883
    #用户名
    username:
    #密码
    password:
    #客户端id（不能重复）
    client:
      id: consumer-id2
    #MQTT默认的消息推送主题，实际可在调用接口时指定
    default:
      topic: arrowgd/sensor/infineon/u/CO2-0102B6GD
#mybatis配置
mybatis:
  config-location: classpath:mybatis/MybatisConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#jwt:
#  secret: 1T7e3t3AhK9kS2DdF6gZr4e7hWmYq3t5vT7e3t3AhK9kS2DdF6gZr4e7hWmYq3t5vT7e3t3AhK9kS2DdF6gZr4e7hWmYq3t5vT7e3t3AhK9kS2DdF6gZr4e7hWmYq3t5v
#  expiration: 864000



